// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { envVars } from "./src/config/env";
export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
        seed: "tsx src/scripts/seedCategory.ts",
    },
    datasource: { url: envVars.DATABASE_URL },
});
